### PR TITLE
Adding Dask-SQL Weather notebook

### PR DESCRIPTION
**Pull request by randerzander**
cc @taureandyernv

### CODE REVIEW

**Comment by randerzander** [comment]
<p>It's on by default. Will make that clearer.</p>

---

 <a href='https://app.reviewnb.com/rapidsai-community/showcase/pull/12/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by randerzander** [comment]
<p>https://github.com/dask-contrib/dask-sql/issues/281</p><p> </p><p>And here, I specifically want the timing and "select * limit 5" behavior. I don't think most users want this by default.</p>

---

 <a href='https://app.reviewnb.com/rapidsai-community/showcase/pull/12/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by randerzander** [comment]
<p>You can. The intent here is to show ability to create tables from both filepaths, and from DataFrames. Will comment to that effect.</p>

---

 <a href='https://app.reviewnb.com/rapidsai-community/showcase/pull/12/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by randerzander** [comment]
<p>This is explained in the markdown cell above. Maybe it wasn't clear enough?</p>

---

 <a href='https://app.reviewnb.com/rapidsai-community/showcase/pull/12/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by randerzander** [comment]
<p>The whole notebook depends on tables created in prior cells. Will make a note at the top about running in order only.</p>

---

 <a href='https://app.reviewnb.com/rapidsai-community/showcase/pull/12/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by randerzander** [comment]
<p>yearly_stations is a table understood by the Dask-SQL context, not a Python variable.</p><p> </p><p>This is how the notebook works for all tables. Is there something specific about this one that made you ask? Or are you noting that should be clearer broadly?</p><p> </p>

---

 <a href='https://app.reviewnb.com/rapidsai-community/showcase/pull/12/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by beckernick** [comment]
<p>I think it's clear that you can do it, but is this the primary/only way? E.g., if I want to mix DF/SQL, should I be doing this or using the SQL magics (which I realize are broken at the moment, per your prior comment). It sounds like the answer is I should be using it like this.</p>

---

 <a href='https://app.reviewnb.com/rapidsai-community/showcase/pull/12/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by beckernick** [comment]
<p>Makes sense. Mostly curious as to whether I could do %%sql ... and then mix in dataframe operations "magically"</p>

---

 <a href='https://app.reviewnb.com/rapidsai-community/showcase/pull/12/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
